name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: cmake -B build && cmake --build build --config Release

    - name: Run tests
      run: ./build/RunTests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-files
        path: build/example 
