name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc g++ cmake

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ./build/tests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-files
        path: build
