name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#виталик жирный
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y cmake

      - name: Configure and Build
        run: |
          cmake -H. -B_build
          cmake --build _build

      - name: Run tests
        run: ctest --test-dir _build --output-on-failure

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-files
          path: _build

